# Generated by Django 5.0.4 on 2025-06-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_djangoadminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id_arquivo', models.IntegerField(db_comment='Identificador único do arquivo (PK).', primary_key=True, serialize=False)),
                ('tamanho', models.IntegerField(db_comment='Tamanho do arquivo em bytes.')),
                ('data_envio', models.DateField(blank=True, db_comment='Data de upload/armazenamento no sistema.', null=True)),
                ('nome', models.CharField(blank=True, db_comment='Nome original do arquivo enviado.', max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, db_comment='Tipo/MIME ou extensão do arquivo (ex: pdf, png, jpeg, docx).', max_length=255, null=True)),
                ('caminho', models.CharField(blank=True, db_comment='Caminho de armazenamento no sistema de arquivos ou URL (se remoto).', max_length=255, null=True)),
            ],
            options={
                'db_table': 'arquivo',
                'db_table_comment': 'A entidade arquivo representa os arquivos digitais vinculados a uma produção acadêmica, técnica, científica ou artística. Ela permite armazenar múltiplos arquivos por produção, servindo como evidência, conteúdo complementar ou documentação comprobatória.\n\nCada registro da tabela arquivo é associado a uma entrada na entidade producao, garantindo a rastreabilidade e a organização dos materiais no sistema.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id_banca', models.IntegerField(db_comment='Identificação unica da banca', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_comment='Ano de realização da banca.')),
                ('data_arguicao', models.DateField(db_comment='Data em que a arguição (apresentação/defesa) ocorreu.')),
                ('data_aprovacao', models.DateField(blank=True, db_comment='Data oficial de aprovação (pode coincidir ou não com a arguição).', null=True)),
                ('tema', models.CharField(db_comment='Título ou tema do trabalho defendido.', max_length=255)),
                ('observacoes', models.CharField(blank=True, db_comment='Campo livre para registrar considerações ou anotações adicionais.', max_length=255, null=True)),
            ],
            options={
                'db_table': 'banca',
                'db_table_comment': 'A entidade banca representa comissões avaliadoras formadas para acompanhar e julgar trabalhos acadêmicos, como defesas de TCC, dissertações ou teses. Cada banca é composta por docentes com diferentes funções (presidente, membro, suplente) e está associada a um tema, a uma data de arguição e, quando aplicável, à data de aprovação.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoDocente',
            fields=[
                ('valor', models.CharField(db_comment='Valor atribuido ao contato, por exemplo se for email: email@email.com ou telefone 9999-99999', max_length=255)),
                ('observacao', models.TextField(blank=True, db_comment='Observações gerais do contato', null=True)),
                ('id_contato', models.IntegerField(db_comment='Identificação unica do contato', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contato_docente',
                'db_table_comment': 'Contatos de um docente, por ex: email, telefone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(db_comment='Identificação do curso', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_comment='Nome do curso', max_length=255)),
                ('area_conhecimento', models.CharField(blank=True, db_comment='Area de conhecimento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'curso',
                'db_table_comment': 'A entidade curso representa uma estrutura acadêmica formal oferecida pela Universidade, composta por um conjunto organizado de disciplinas que definem sua grade curricular. Cada curso é associado a uma área do conhecimento, a um tipo (como bacharelado, licenciatura, tecnólogo, especialização etc.) e está vinculado a um instituto ou unidade de ensino responsável por sua oferta.\n\nOs cursos são definidos por:\n\t•\tNome e tipo do curso\n\t•\tÁrea do conhecimento\n\t•\tInstituição de origem (ex: Instituto ou Departamento)\n\t•\tDisciplinas obrigatórias e optativas\n\t•\tEstrutura curricular por fases, semestres ou módulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(db_comment='Identificação única do departamento', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_comment='Nome  do departamento', max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, db_comment='Siga do departamento', max_length=255, null=True)),
                ('chefe', models.CharField(blank=True, db_comment='Nome do chefe do departamento', max_length=255, null=True)),
                ('vice_chefe', models.CharField(blank=True, db_comment='Nome do vice chefe do departamento', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição e finalidade do departamento', null=True)),
                ('endereco', models.CharField(blank=True, db_comment='Enderço interno do departamento', max_length=255, null=True)),
                ('numero_docentes', models.IntegerField(blank=True, db_comment='Número de docentes do departamento', null=True)),
                ('ano_fundacao', models.IntegerField(blank=True, db_comment='Ano de fundação do departamento', null=True)),
            ],
            options={
                'db_table': 'departamento',
                'db_table_comment': 'A entidade departamento representa uma subunidade acadêmica vinculada a um instituto, responsável por coordenar atividades de ensino, pesquisa e extensão em áreas específicas do conhecimento. Armazena informações administrativas e acadêmicas como nome, sigla, descrição institucional, endereço interno, número de docentes, ano de fundação e a chefia atual.\n\nCada departamento está diretamente associado a um instituto, do qual herda sua estrutura organizacional e participa da oferta de cursos, disciplinas e da alocação de docentes.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.IntegerField(db_comment='Identificação da disciplina', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_comment='Nome da disciplina', max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, db_comment='Sigla de indentificação da disciplina', null=True)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do conteúdo da disciplina', null=True)),
                ('carga_horaria', models.IntegerField(blank=True, db_comment='Carga horária atribuida a disciplina', null=True)),
                ('creditos', models.IntegerField(blank=True, db_comment='Quando créditos a matéria oferece', null=True)),
                ('idioma', models.CharField(blank=True, db_comment='Idioma que é oferecido a disciplina', max_length=255, null=True)),
                ('modalidade', models.CharField(blank=True, db_comment='Qual é a modealidade do oferecimento, por exemplo: presencial, online, híbrido', max_length=255, null=True)),
                ('link_jupiter', models.CharField(blank=True, db_comment='Url para o sistema de apoio a matricula da USP', max_length=255, null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'db_table_comment': 'A entidade disciplina representa o cadastro básico e estruturado das disciplinas oferecidas pela Universidade. Ela funciona como referência central para todos os oferecimentos curriculares, reunindo as informações essenciais e perenes que caracterizam cada componente curricular.\n\nCada registro de disciplina inclui dados como:\n\t•\tNome e sigla identificadora\n\t•\tEmenta e descrição geral do conteúdo (descrita no link do jupterweb)\n\t•\tCarga horária total e número de créditos\n\t•\tModalidade (presencial, online, híbrida)\n\t•\tIdioma de instrução, quando aplicável\n\nEssa entidade não está vinculada a um período específico, servindo como base para os múltiplos oferecimentos semestrais, modelados separadamente pela entidade edição de disciplina.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_comment='Nome do docente', max_length=255)),
                ('genero', models.CharField(blank=True, db_comment='Genero definido pelo docente', null=True)),
                ('raca', models.CharField(blank=True, db_comment='Raça definida pelo docente', max_length=255, null=True)),
                ('nascimento', models.DateField(db_comment='data de nascimento')),
                ('palavras_chave', models.TextField(blank=True, db_comment='Palavras que chaves usandas na busca para selecionar o docente', null=True)),
            ],
            options={
                'db_table': 'docente',
                'db_table_comment': 'A entidade docente representa os professores vinculados à Universidade, responsáveis por atividades de ensino, pesquisa, orientação, participação em bancas e produção acadêmica. Ela armazena os dados essenciais para identificação, caracterização e relacionamento dos docentes com os demais elementos do sistema acadêmico.\n\nEntre os atributos armazenados estão informações pessoais, acadêmicas e institucionais, tais como nome, gênero, raça, data de nascimento, palavras-chave de atuação e vínculo com o departamento de origem.\n\nEssa entidade é central no modelo, sendo relacionada a disciplinas, orientações, produções, bancas, cursos e outras estruturas institucionais.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docenteproducaoartistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'docenteproducaoartistica',
                'db_table_comment': 'Uma produção artistica pode ter vários autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docenteproducaobibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'docenteproducaobibliografica',
                'db_table_comment': 'Produção científica dos docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docenteproducaotecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'docenteproducaotecnica',
                'db_table_comment': 'Uma produção técnica pode ser desenvolvida em parcerias com outras pessoas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edicaodisciplina',
            fields=[
                ('id_edicao', models.IntegerField(db_comment='Identifcação do oferecimento', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, db_comment='Ano em que esta sendo oferecida a disciplina', null=True)),
                ('semestre', models.CharField(blank=True, db_comment='Semestre de oferencimento', null=True)),
                ('numero_alunos', models.IntegerField(blank=True, db_comment='Número de alunos matriculados na disciplina', null=True)),
                ('link_avaliacao', models.CharField(blank=True, db_comment='Link para o sistema e-disciplina, ou outro sistema onde estão resgistrada as notas', null=True)),
            ],
            options={
                'db_table': 'edicaodisciplina',
                'db_table_comment': 'Uma edição de disciplina representa o oferecimento concreto de uma disciplina em um determinado semestre e ano letivo, podendo ainda estar associada a uma turma específica. Essa edição está vinculada à disciplina base, que funciona como um cadastro genérico e perene contendo as informações estruturais da disciplina — como nome, sigla, ementa, carga horária e créditos.\n\nA edição, por sua vez, contém os dados variáveis e contextuais do oferecimento, tais como:\n\t•\tPeríodo letivo (ano e semestre)\n\t•\tNúmero de alunos matriculados\n\t•\tLocal de realização\n\t•\tDocentes responsáveis\n\t•\tLinks para sistema acadêmico ou avaliações\n\nEsse modelo permite distinguir a identidade estável da disciplina de suas múltiplas implementações ao longo do tempo.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecoDocente',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(db_comment='Rua, avenida, etc', max_length=255)),
                ('numero', models.CharField(blank=True, db_comment='Número do endereço, é um varchar pois pode ser S/N.', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, db_comment='Complemento do endereço', max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, db_comment='Bairro do endereço', max_length=255, null=True)),
                ('cidade', models.CharField(db_comment='Cidade do endereço', max_length=255)),
                ('estado', models.CharField(db_comment='Estado do endereço', max_length=255)),
                ('cep', models.CharField(blank=True, db_comment='CEP do endereço', max_length=10, null=True)),
                ('pais', models.CharField(blank=True, db_comment='País do endereço', max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, db_comment='Observações sobre o endereço do docente', null=True)),
            ],
            options={
                'db_table': 'endereco_docente',
                'db_table_comment': 'Endereço do docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncaoParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_participacao', models.CharField(blank=True, db_comment='Nome da fução, é chave primária', max_length=50, null=True, unique=True)),
                ('descricao', models.CharField(blank=True, db_comment='Descrição das contribuições dadas pelo participante.', max_length=255, null=True)),
            ],
            options={
                'db_table': 'funcao_participacao',
                'db_table_comment': 'Cada autor do documento técnico pode ter uma participação específica na elabaoração do documento, por exemplo:\nautor_principal: Criador principal da versão\ncoautor: Contribuição relevante, mas secundária\nrevisor: Revisão técnica ou textual\nresponsavel_design: Autor da parte gráfica ou layout\ndesenvolvedor: Se a produção for um software\nconsultor: Contribuição externa, não autoral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id_instituto', models.IntegerField(db_comment='Identificação unica do instituto', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_comment='Nome do instituto', max_length=255, null=True)),
                ('numero_docentes', models.IntegerField(blank=True, db_comment='Número mas recente de docentes  do instituto', null=True)),
                ('ano_fundacao', models.IntegerField(blank=True, db_comment='Ano de fundação  do instituto', null=True)),
                ('numero_alunos', models.IntegerField(blank=True, db_comment='Número de alunos  do instituto', null=True)),
                ('diretor', models.CharField(blank=True, db_comment='Nome do diretor  do instituto', max_length=255, null=True)),
                ('vice_diretor', models.CharField(blank=True, db_comment='Nome do  vice diretor do instituto', max_length=255, null=True)),
                ('site', models.CharField(blank=True, db_comment='Url  do instituto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'instituto',
                'db_table_comment': 'A entidade instituto representa uma unidade acadêmica da Universidade, responsável pela oferta de cursos, disciplinas e pela vinculação de docentes e departamentos. Armazena informações institucionais  como nome, número de docentes e alunos, ano de fundação, direção atual, site institucional e localização física (referenciada pela entidade local).\n\nEssa entidade serve como ponto de origem organizacional para a estrutura acadêmica e administrativa do sistema.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_local', models.IntegerField(db_comment='Identificação unica do local', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_comment='Nome dado ao local', max_length=255, null=True)),
                ('localizacao', models.CharField(blank=True, db_comment='A localização pode um endereço ou um local virtual', max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, db_comment='Quando é um local físico pode ser interessante fazer a idade do local', null=True)),
                ('data_ultima_reforma', models.DateField(blank=True, db_comment='Se for um local físico existe informações sobre a ultima reforma', null=True)),
                ('numero_salas', models.IntegerField(blank=True, db_comment='Quantidade de salas do local físico ou virtual', null=True)),
                ('numero_blocos', models.IntegerField(blank=True, db_comment='Númro de blocos do local físico', null=True)),
            ],
            options={
                'db_table': 'localizacao',
                'db_table_comment': 'A localização representa um local físico ou lógico (como um ambiente virtual)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id_orientacao', models.IntegerField(db_comment='identificação da orientação', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(blank=True, db_comment='Ano que em se iniciou a orientação', null=True)),
                ('nome_orientado', models.CharField(db_comment='Nome do orientado', max_length=255)),
                ('data_inicio', models.DateField(db_comment='Data que se iniciou a orientação')),
                ('data_fim', models.DateField(blank=True, db_comment='Data de finalização da orientação', null=True)),
                ('observacoes', models.TextField(blank=True, db_comment='Observações gerais sobre a orientação', null=True)),
                ('titulo_trabalho', models.CharField(blank=True, db_comment='Titulo do trabalho desenvolvido', max_length=255, null=True)),
            ],
            options={
                'db_table': 'orientacao',
                'db_table_comment': 'A entidade orientação registra o vínculo entre docentes e estudantes em projetos acadêmicos orientados, como trabalhos de conclusão de curso, dissertações de mestrado ou teses de doutorado. Cada orientação possui um tipo (TCC, mestrado, doutorado etc.), tema, período de vigência e situação atual (em andamento, concluída, cancelada).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premiotitulo',
            fields=[
                ('id_premio_titulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_comment='Nome do prêmio', max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, db_comment='Ano do prêmio dado a docentes', null=True)),
            ],
            options={
                'db_table': 'premiotitulo',
                'db_table_comment': 'Prêmios recebidos pelos docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producaobibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn_isbn', models.CharField(blank=True, db_comment='Número identificador da obra (ISSN para periódicos, ISBN para livros).', max_length=255, null=True)),
                ('nome_periodico', models.CharField(blank=True, db_comment='Nome do periódico, revista ou veículo de publicação.', max_length=255, null=True)),
                ('volume', models.CharField(blank=True, db_comment='Volume ou coleção em que a produção foi publicada.', max_length=255, null=True)),
                ('numero', models.CharField(blank=True, db_comment='Número do volume ou edição.', max_length=255, null=True)),
                ('doi', models.CharField(blank=True, db_comment='DOI (Digital Object Identifier) da publicação, quando disponível.', max_length=255, null=True)),
                ('data_publicacao', models.DateField(blank=True, db_comment='Data de publicação oficial.', null=True)),
                ('id_producao', models.IntegerField(db_comment='Id de referência da gereneralização, pois essa entidade é uma especialização.', unique=True)),
                ('paginas', models.IntegerField(blank=True, db_comment='Quantidade de páginas publicadas.', null=True)),
                ('local_publicacao', models.CharField(blank=True, db_comment='Cidade, estado ou país da publicação.', max_length=255, null=True)),
                ('editora', models.CharField(blank=True, db_comment='Nome da editora responsável pela publicação.', max_length=255, null=True)),
            ],
            options={
                'db_table': 'producaobibliografica',
                'db_table_comment': 'A entidade producaobibliografica representa uma especialização da entidade genérica produção, destinada ao registro das produções científicas realizadas por docentes da Universidade. Ela abrange publicações acadêmicas como artigos em periódicos, capítulos de livros, livros completos, resumos em anais de eventos, editoriais, entre outros.\n\nAlém dos campos herdados da entidade producao (como título, tipo, ano e vínculo com docentes), a producaobibliografica adiciona um conjunto de atributos específicos para descrever com precisão os dados bibliográficos da publicação:',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producaotecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(blank=True, db_comment='Versão da produção técnica v1, v2, final', null=True)),
                ('id_producao_anterior', models.IntegerField(blank=True, db_comment='Id de referência de onde foi derivada a versão, é uma auto referência.', null=True)),
                ('id_producao', models.IntegerField(blank=True, db_comment='Id de referência da gereneralização, pois essa entidade é uma especialização.', null=True, unique=True)),
            ],
            options={
                'db_table': 'producaotecnica',
                'db_table_comment': 'A entidade produção técnica representa o registro e a catalogação das produções de natureza técnica desenvolvidas por docentes da Universidade, como softwares, relatórios, manuais, protótipos, serviços técnicos, entre outros.\n\nCada produção técnica pode possuir várias versões, permitindo rastrear a evolução do conteúdo ao longo do tempo. O modelo adota uma estrutura de versionamento encadeado, onde:\n\t•\tCada versão aponta para a versão anterior da qual foi derivada (id_versao_anterior);\n\t•\tA primeira versão possui esse campo nulo;\n\t•\tQuando uma versão é derivada, ela herda o conteúdo da versão anterior, que passa a ser imutável no sistema;\n\t•\tTodas as alterações posteriores devem ser feitas na nova versão, garantindo o histórico de modificações e a rastreabilidade.\n\nEssa abordagem oferece:\n\t•\tControle de integridade e rastreamento das alterações;\n\t•\tSuporte a múltiplos autores em cada versão, com papéis distintos (ex: desenvolvedor, editor, responsável técnico);\n\t•\tPossibilidade de vincular cada versão a métricas específicas, avaliações ou registros legais (como INPI, ISBN, DOI etc.).',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacaoOrientacao',
            fields=[
                ('situacao', models.CharField(db_comment='Identificação da situação da orientação', primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição e finalidade da orientação', null=True)),
            ],
            options={
                'db_table': 'situacao_orientacao',
                'db_table_comment': 'Uma orientação possui estagios de acompanhamento, por exemplo:\nandamento: Orientação em andamento\nconcluida: Orientação concluída com sucesso\ncancelada: Orientação cancelada ou interrompida\nsuspensa: Orientação temporariamente suspensa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBanca',
            fields=[
                ('tipo', models.CharField(db_comment='Tipo de banca (ex: TCC, Mestrado, Doutorado,Qualificação (M/D)).', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do tipo de banca e finalidade', null=True)),
            ],
            options={
                'db_table': 'tipo_banca',
                'db_table_comment': 'Tipo de banca que o docente participa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('tipo_contato', models.CharField(db_comment='Nome do tipo de contato, por ex: email, telefone', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do tipo de contato', null=True)),
            ],
            options={
                'db_table': 'tipo_contato',
                'db_table_comment': 'Tipo de contato do docente.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('tipo', models.CharField(db_comment='Nome do tipo de curso', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do curso oferecido', null=True)),
            ],
            options={
                'db_table': 'tipo_curso',
                'db_table_comment': 'Tipo de curso que pode ser regular, de versão, de pós, etc.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEndereco',
            fields=[
                ('tipo_endereco', models.CharField(db_comment='Chave primária do tipo de endereço: residencial, comercial, etc.', max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_comment='Descrição do tipo de endereço', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_endereco',
                'db_table_comment': 'Tipo de endereço que o docente pode esta associado, por ex:\nComercial\nResidêncial\nTemporário',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOrientacao',
            fields=[
                ('tipo', models.CharField(db_comment='Nome do tipo de orientação, ex: tcc, mestrado, doutorado, etc.', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição e finalidade do tipo de orientação', null=True)),
            ],
            options={
                'db_table': 'tipo_orientacao',
                'db_table_comment': 'Tipo de orientação que o docente participa, por ex:\ntcc: Trabalho de Conclusão de Curso\nmestrado: Dissertação de Mestrado\ndoutorado: Tese de Doutorado\niniciacao: Iniciação Científica\nposdoc: Pós-Doutorado\nespecializacao: Monografia de Especialização',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducao',
            fields=[
                ('tipo', models.CharField(db_comment='Tipo de produção', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do objetivo do documento técnico.', null=True)),
            ],
            options={
                'db_table': 'tipo_producao',
                'db_table_comment': 'Tipo de produção desenvolvida pelos docentes:\nPara documentos científicos:\nartigo_periodico: Artigo em periódico\nartigo_evento: Artigo em anais de evento\nlivro: Livro completo\ncapitulo_livro: Capítulo de livro\nresumo_expandido: Resumo expandido\nresumo_simples: Resumo simples\neditorial: Editorial\noutro: Outro tipo de produção\n\n\nPara documentos técnicos:\nsoftware: Desenvolvimento de sistemas ou aplicações.\nrelatorio_tecnico: Documentos técnicos, pareceres ou relatórios institucionais.\nmanual_tecnico: Guias de uso ou operação de equipamentos, sistemas ou processos.\npatente: Pedido ou concessão de patente técnica ou de invenção.\nregistro_programa: Registro oficial de programas de computador (ex: INPI).\nprototipo: Construção de protótipos funcionais ou conceituais.\nprojeto_tecnico: Projeto de engenharia, arquitetura, computação, etc.\nmaquete: Representações físicas ou virtuais de projetos técnicos.\ndesenho_industrial: Criação de design técnico aplicado à indústria.\ndesenvolvimento_material_didatico: Produção de conteúdo técnico com fins educacionais.\ndesenvolvimento_multimidia: Jogos, vídeos interativos, animações técnicas.\neditoração_tecnica: Coordenação técnica de periódicos, livros ou materiais.\nparecer_tecnico: Avaliação formal técnica sobre projetos, produtos ou serviços.\naplicativo_mobile: Aplicações técnicas desenvolvidas para dispositivos móveis.\nbase_dados: Estruturas organizadas de dados técnicos, estatísticos ou científicos.\nservico_tecnico_especializado: Atividades técnicas prestadas como consultoria ou assessoria.\noutro: Produções técnicas não classificadas acima.\n\nPara arte:\nArte contemporânea\nArte clássica\nArte de rua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('vinculo', models.CharField(db_comment='Nome do vículo que chave primária', max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição do vínculo', null=True)),
            ],
            options={
                'db_table': 'vinculo',
                'db_table_comment': 'Os docentes podem assumir diferentes formas de participação em diversas atividades acadêmicas, como produções técnicas e bibliográficas, orientações, bancas examinadoras e disciplinas lecionadas. Esta entidade centraliza os tipos de vínculo existentes entre o docente e os elementos do sistema em que ele atua, permitindo a padronização e reutilização desses papeis em diferentes contextos.\n\nA seguir, são apresentados exemplos de tipos de vínculo organizados por escopo:\n\nPara banca:\npresidente\nmembro\nsuplente\navaliador externo\norientador (caso a banca inclua o orientador formalmente)\nrelator (se aplicável em dissertações/tese)\n\nPara orientação:\norientador\ncoorientador\n\nPara produção bibliografica:\n autor\n coautor\n organizador\n editor técnico\n tradutor\n\nPara docente na disciplina:\nministrante\ncoordenador\nauxiliar',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.CreateModel(
            name='Cursodisciplina',
            fields=[
                ('id_curso', models.OneToOneField(db_column='id_curso', db_comment='Qual é o curso na grade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.curso')),
                ('obrigatoria', models.BooleanField(blank=True, db_comment='Se é uma disciplina obrigatória no curso', null=True)),
                ('semestre_ideal', models.IntegerField(blank=True, db_comment='Qual é o semestre ideal que a matéria é ofereciada', null=True)),
            ],
            options={
                'db_table': 'cursodisciplina',
                'db_table_comment': 'A associação entre curso e disciplina permite compor a matriz curricular, definindo quais disciplinas são obrigatórias, em que fase são ofertadas, e suas características específicas dentro do contexto do curso.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentebanca',
            fields=[
                ('id_docente', models.OneToOneField(db_column='id_docente', db_comment='Identificação do docente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.docente')),
            ],
            options={
                'db_table': 'docentebanca',
                'db_table_comment': 'Bancas que um docente participou',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docenteedicaodisciplina',
            fields=[
                ('id_docente', models.OneToOneField(db_column='id_docente', db_comment='Docente que participa da disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.docente')),
                ('carga_horaria_ministrada', models.IntegerField(blank=True, db_comment='Carga horária desse ofereciemnto em específico', null=True)),
            ],
            options={
                'db_table': 'docenteedicaodisciplina',
                'db_table_comment': 'A disciplina é ofertada por edição (semestre/ano/turma), assim um docente pode ficar vinculado as edições das disciplina que já participou. Uma disciplina pode ser mistrada por vários docentes.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentehabilitacaodisciplina',
            fields=[
                ('id_docente', models.OneToOneField(db_column='id_docente', db_comment='Docente que pode participar desta disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.docente')),
            ],
            options={
                'db_table': 'docentehabilitacaodisciplina',
                'db_table_comment': 'Os docentes são associados somente as disciplinas que estão aptos a lecionar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docenteorientacao',
            fields=[
                ('id_docente', models.OneToOneField(db_column='id_docente', db_comment='Docente responsável pela orientação', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.docente')),
            ],
            options={
                'db_table': 'docenteorientacao',
                'db_table_comment': 'Orientações de um docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentepremiotitulo',
            fields=[
                ('id_docente', models.OneToOneField(db_column='id_docente', db_comment='Docente que recebe o prêmio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.docente')),
                ('data_recebimento', models.DateField(blank=True, db_comment='Data de recebimento do prêmio. É possível que o prêmio seja entregue em datas distintas quando o prêmio é compartilhado.', null=True)),
            ],
            options={
                'db_table': 'docentepremiotitulo',
                'db_table_comment': 'Um prêmio pode ser dado a vários docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id_producao', models.OneToOneField(db_column='id_producao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.producaobibliografica')),
                ('descricao', models.TextField(db_comment='Descrição da produção')),
                ('ano', models.IntegerField(db_comment='Ano em que foi criado a produção.')),
                ('data_producao', models.DateField(blank=True, db_comment='Data de finalização ou catalogação da produção.', null=True)),
                ('observacao', models.TextField(blank=True, db_comment='Observações', null=True)),
                ('nome', models.CharField(db_comment='Nome da produção', max_length=255)),
                ('titulo', models.CharField(db_comment='Título da produção', max_length=255)),
            ],
            options={
                'db_table': 'producao',
                'db_table_comment': 'A entidade produção representa uma generalização dos diversos tipos de trabalhos desenvolvidos pelos docentes no âmbito acadêmico e profissional. Essa estrutura unificada permite organizar e rastrear todas as formas de produção realizadas por um docente, sejam elas de natureza científica, técnica ou artística.\n\nCada produção é vinculada a um docente (ou a vários, em coautoria), e pode assumir diferentes especializações, como:\n\t•\tProdução Bibliográfica: artigos, livros, capítulos, resumos, etc.\n\t•\tProdução Técnica: softwares, relatórios, projetos, patentes, etc.\n\t•\tProdução Artística: obras plásticas, exposições, performances, etc.\n\nA entidade genérica producao reúne os campos comuns (como título, ano, tipo, vinculação ao docente), enquanto as entidades especializadas estendem essas informações com atributos específicos conforme o tipo da produção.\n\nEssa abordagem favorece:\n\t•\tReutilização de estrutura e consultas unificadas;\n\t•\tFlexibilidade para incluir novos tipos de produção;\n\t•\tAdoção de herança em modelagem orientada a objetos ou estruturas EER.',
                'managed': False,
            },
        ),
    ]
